name: "Visual Snapshots: report-ui"

on:
  pull_request:
  workflow_dispatch:
    inputs:
      baseline_branch:
        description: Branch to use as baseline snapshots source.
        required: false
        default: main
      report_branch:
        description: Branch to use for report/diff snapshots source.
        required: false
      fail_on_changes:
        description: Fail workflow when changed snapshots are detected.
        type: boolean
        required: false
        default: false

permissions:
  contents: write
  pull-requests: write

jobs:
  visual-snapshots:
    name: "Visual Snapshots: report-ui"
    uses: ./.github/workflows/reusable-visual-snapshots.yml
    with:
      label: report-ui
      folder: packages/report-ui
      baseline_branch: ${{ github.event_name == 'pull_request' && github.base_ref || inputs.baseline_branch || 'main' }}
      report_branch: ${{ github.event_name == 'pull_request' && github.head_ref || inputs.report_branch || github.ref_name }}
      fail_on_changes: ${{ inputs.fail_on_changes || false }}
    secrets: inherit
